//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sistemaAGP.swventasoap {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="swventasoap.ServiceSoap")]
    public interface ServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EmitirVentaSoap", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        sistemaAGP.swventasoap.RespuestaVentaSoap EmitirVentaSoap(string xml);
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(RespuestaErrorVentaSoap))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(RespuestaSalidaVentaSoap))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public abstract partial class RespuestaVentaSoap : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int codigoEstadoField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int CodigoEstado {
            get {
                return this.codigoEstadoField;
            }
            set {
                this.codigoEstadoField = value;
                this.RaisePropertyChanged("CodigoEstado");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class DescripcionRespuestaVentaSoap : object, System.ComponentModel.INotifyPropertyChanged {
        
        private long numeroPolizaField;
        
        private long numeroFolioField;
        
        private string vigenciaDesdeField;
        
        private string vigenciahastaField;
        
        private string urlPolizaSoapField;
        
        private string numeroPatenteField;
        
        private string digitoVerificadorPatenteField;
        
        private string tipoVehiculoField;
        
        private string numeroMotorField;
        
        private int anioField;
        
        private string marcaField;
        
        private string modeloField;
        
        private System.Nullable<int> rutPropietarioField;
        
        private string digitoVerificadorPropietarioField;
        
        private string nombreField;
        
        private string apellidoPaternoField;
        
        private string apellidoMaternoField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public long NumeroPoliza {
            get {
                return this.numeroPolizaField;
            }
            set {
                this.numeroPolizaField = value;
                this.RaisePropertyChanged("NumeroPoliza");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public long NumeroFolio {
            get {
                return this.numeroFolioField;
            }
            set {
                this.numeroFolioField = value;
                this.RaisePropertyChanged("NumeroFolio");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string VigenciaDesde {
            get {
                return this.vigenciaDesdeField;
            }
            set {
                this.vigenciaDesdeField = value;
                this.RaisePropertyChanged("VigenciaDesde");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Vigenciahasta {
            get {
                return this.vigenciahastaField;
            }
            set {
                this.vigenciahastaField = value;
                this.RaisePropertyChanged("Vigenciahasta");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string UrlPolizaSoap {
            get {
                return this.urlPolizaSoapField;
            }
            set {
                this.urlPolizaSoapField = value;
                this.RaisePropertyChanged("UrlPolizaSoap");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string NumeroPatente {
            get {
                return this.numeroPatenteField;
            }
            set {
                this.numeroPatenteField = value;
                this.RaisePropertyChanged("NumeroPatente");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string DigitoVerificadorPatente {
            get {
                return this.digitoVerificadorPatenteField;
            }
            set {
                this.digitoVerificadorPatenteField = value;
                this.RaisePropertyChanged("DigitoVerificadorPatente");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string TipoVehiculo {
            get {
                return this.tipoVehiculoField;
            }
            set {
                this.tipoVehiculoField = value;
                this.RaisePropertyChanged("TipoVehiculo");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string NumeroMotor {
            get {
                return this.numeroMotorField;
            }
            set {
                this.numeroMotorField = value;
                this.RaisePropertyChanged("NumeroMotor");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public int Anio {
            get {
                return this.anioField;
            }
            set {
                this.anioField = value;
                this.RaisePropertyChanged("Anio");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string Marca {
            get {
                return this.marcaField;
            }
            set {
                this.marcaField = value;
                this.RaisePropertyChanged("Marca");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string Modelo {
            get {
                return this.modeloField;
            }
            set {
                this.modeloField = value;
                this.RaisePropertyChanged("Modelo");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=12)]
        public System.Nullable<int> RutPropietario {
            get {
                return this.rutPropietarioField;
            }
            set {
                this.rutPropietarioField = value;
                this.RaisePropertyChanged("RutPropietario");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string DigitoVerificadorPropietario {
            get {
                return this.digitoVerificadorPropietarioField;
            }
            set {
                this.digitoVerificadorPropietarioField = value;
                this.RaisePropertyChanged("DigitoVerificadorPropietario");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public string Nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("Nombre");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public string ApellidoPaterno {
            get {
                return this.apellidoPaternoField;
            }
            set {
                this.apellidoPaternoField = value;
                this.RaisePropertyChanged("ApellidoPaterno");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public string ApellidoMaterno {
            get {
                return this.apellidoMaternoField;
            }
            set {
                this.apellidoMaternoField = value;
                this.RaisePropertyChanged("ApellidoMaterno");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class RespuestaErrorVentaSoap : RespuestaVentaSoap {
        
        private string descripcionErrorField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string descripcionError {
            get {
                return this.descripcionErrorField;
            }
            set {
                this.descripcionErrorField = value;
                this.RaisePropertyChanged("descripcionError");
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class RespuestaSalidaVentaSoap : RespuestaVentaSoap {
        
        private DescripcionRespuestaVentaSoap descripcionField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public DescripcionRespuestaVentaSoap Descripcion {
            get {
                return this.descripcionField;
            }
            set {
                this.descripcionField = value;
                this.RaisePropertyChanged("Descripcion");
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServiceSoapChannel : sistemaAGP.swventasoap.ServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceSoapClient : System.ServiceModel.ClientBase<sistemaAGP.swventasoap.ServiceSoap>, sistemaAGP.swventasoap.ServiceSoap {
        
        public ServiceSoapClient() {
        }
        
        public ServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public sistemaAGP.swventasoap.RespuestaVentaSoap EmitirVentaSoap(string xml) {
            return base.Channel.EmitirVentaSoap(xml);
        }
    }
}
