//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sistemaAGP.IntegracionIndumotora {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Respuesta", Namespace="http://serinfo.cl/")]
    [System.SerializableAttribute()]
    public partial class Respuesta : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Xml.Linq.XElement Mae_AdquirienteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Xml.Linq.XElement Mae_CompraParaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Xml.Linq.XElement Mae_DatosVehiculosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Xml.Linq.XElement Mae_FacturasField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Xml.Linq.XElement Mae_TramitesVehiculosField;
        
        private System.DateTime FechaInicioField;
        
        private System.DateTime FechaTerminoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescripcionField;
        
        private short CodigoRetornoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public System.Xml.Linq.XElement Mae_Adquiriente {
            get {
                return this.Mae_AdquirienteField;
            }
            set {
                if ((object.ReferenceEquals(this.Mae_AdquirienteField, value) != true)) {
                    this.Mae_AdquirienteField = value;
                    this.RaisePropertyChanged("Mae_Adquiriente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public System.Xml.Linq.XElement Mae_CompraPara {
            get {
                return this.Mae_CompraParaField;
            }
            set {
                if ((object.ReferenceEquals(this.Mae_CompraParaField, value) != true)) {
                    this.Mae_CompraParaField = value;
                    this.RaisePropertyChanged("Mae_CompraPara");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public System.Xml.Linq.XElement Mae_DatosVehiculos {
            get {
                return this.Mae_DatosVehiculosField;
            }
            set {
                if ((object.ReferenceEquals(this.Mae_DatosVehiculosField, value) != true)) {
                    this.Mae_DatosVehiculosField = value;
                    this.RaisePropertyChanged("Mae_DatosVehiculos");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public System.Xml.Linq.XElement Mae_Facturas {
            get {
                return this.Mae_FacturasField;
            }
            set {
                if ((object.ReferenceEquals(this.Mae_FacturasField, value) != true)) {
                    this.Mae_FacturasField = value;
                    this.RaisePropertyChanged("Mae_Facturas");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public System.Xml.Linq.XElement Mae_TramitesVehiculos {
            get {
                return this.Mae_TramitesVehiculosField;
            }
            set {
                if ((object.ReferenceEquals(this.Mae_TramitesVehiculosField, value) != true)) {
                    this.Mae_TramitesVehiculosField = value;
                    this.RaisePropertyChanged("Mae_TramitesVehiculos");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public System.DateTime FechaInicio {
            get {
                return this.FechaInicioField;
            }
            set {
                if ((this.FechaInicioField.Equals(value) != true)) {
                    this.FechaInicioField = value;
                    this.RaisePropertyChanged("FechaInicio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public System.DateTime FechaTermino {
            get {
                return this.FechaTerminoField;
            }
            set {
                if ((this.FechaTerminoField.Equals(value) != true)) {
                    this.FechaTerminoField = value;
                    this.RaisePropertyChanged("FechaTermino");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string Descripcion {
            get {
                return this.DescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripcionField, value) != true)) {
                    this.DescripcionField = value;
                    this.RaisePropertyChanged("Descripcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=8)]
        public short CodigoRetorno {
            get {
                return this.CodigoRetornoField;
            }
            set {
                if ((this.CodigoRetornoField.Equals(value) != true)) {
                    this.CodigoRetornoField = value;
                    this.RaisePropertyChanged("CodigoRetorno");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://serinfo.cl/", ConfigurationName="IntegracionIndumotora.WService_agp_autoproSoap")]
    public interface WService_agp_autoproSoap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento idEmpresa del espacio de nombres http://serinfo.cl/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://serinfo.cl/Integra_Agp", ReplyAction="*")]
        sistemaAGP.IntegracionIndumotora.Integra_AgpResponse Integra_Agp(sistemaAGP.IntegracionIndumotora.Integra_AgpRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Integra_AgpRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Integra_Agp", Namespace="http://serinfo.cl/", Order=0)]
        public sistemaAGP.IntegracionIndumotora.Integra_AgpRequestBody Body;
        
        public Integra_AgpRequest() {
        }
        
        public Integra_AgpRequest(sistemaAGP.IntegracionIndumotora.Integra_AgpRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://serinfo.cl/")]
    public partial class Integra_AgpRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string idEmpresa;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Numero_Documento;
        
        public Integra_AgpRequestBody() {
        }
        
        public Integra_AgpRequestBody(string idEmpresa, string Numero_Documento) {
            this.idEmpresa = idEmpresa;
            this.Numero_Documento = Numero_Documento;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Integra_AgpResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Integra_AgpResponse", Namespace="http://serinfo.cl/", Order=0)]
        public sistemaAGP.IntegracionIndumotora.Integra_AgpResponseBody Body;
        
        public Integra_AgpResponse() {
        }
        
        public Integra_AgpResponse(sistemaAGP.IntegracionIndumotora.Integra_AgpResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://serinfo.cl/")]
    public partial class Integra_AgpResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public sistemaAGP.IntegracionIndumotora.Respuesta Integra_AgpResult;
        
        public Integra_AgpResponseBody() {
        }
        
        public Integra_AgpResponseBody(sistemaAGP.IntegracionIndumotora.Respuesta Integra_AgpResult) {
            this.Integra_AgpResult = Integra_AgpResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WService_agp_autoproSoapChannel : sistemaAGP.IntegracionIndumotora.WService_agp_autoproSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WService_agp_autoproSoapClient : System.ServiceModel.ClientBase<sistemaAGP.IntegracionIndumotora.WService_agp_autoproSoap>, sistemaAGP.IntegracionIndumotora.WService_agp_autoproSoap {
        
        public WService_agp_autoproSoapClient() {
        }
        
        public WService_agp_autoproSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WService_agp_autoproSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WService_agp_autoproSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WService_agp_autoproSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        sistemaAGP.IntegracionIndumotora.Integra_AgpResponse sistemaAGP.IntegracionIndumotora.WService_agp_autoproSoap.Integra_Agp(sistemaAGP.IntegracionIndumotora.Integra_AgpRequest request) {
            return base.Channel.Integra_Agp(request);
        }
        
        public sistemaAGP.IntegracionIndumotora.Respuesta Integra_Agp(string idEmpresa, string Numero_Documento) {
            sistemaAGP.IntegracionIndumotora.Integra_AgpRequest inValue = new sistemaAGP.IntegracionIndumotora.Integra_AgpRequest();
            inValue.Body = new sistemaAGP.IntegracionIndumotora.Integra_AgpRequestBody();
            inValue.Body.idEmpresa = idEmpresa;
            inValue.Body.Numero_Documento = Numero_Documento;
            sistemaAGP.IntegracionIndumotora.Integra_AgpResponse retVal = ((sistemaAGP.IntegracionIndumotora.WService_agp_autoproSoap)(this)).Integra_Agp(inValue);
            return retVal.Body.Integra_AgpResult;
        }
    }
}
