//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sistemaAGP.integracionAG {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="integracionAG.WSIntegracionAGPSoap")]
    public interface WSIntegracionAGPSoap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento username del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetFacturaPorNumero", ReplyAction="*")]
        sistemaAGP.integracionAG.GetFacturaPorNumeroResponse GetFacturaPorNumero(sistemaAGP.integracionAG.GetFacturaPorNumeroRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento username del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetFacturasPorFechas", ReplyAction="*")]
        sistemaAGP.integracionAG.GetFacturasPorFechasResponse GetFacturasPorFechas(sistemaAGP.integracionAG.GetFacturasPorFechasRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento texto del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Encriptar", ReplyAction="*")]
        sistemaAGP.integracionAG.EncriptarResponse Encriptar(sistemaAGP.integracionAG.EncriptarRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetFacturaPorNumeroRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetFacturaPorNumero", Namespace="http://tempuri.org/", Order=0)]
        public sistemaAGP.integracionAG.GetFacturaPorNumeroRequestBody Body;
        
        public GetFacturaPorNumeroRequest() {
        }
        
        public GetFacturaPorNumeroRequest(sistemaAGP.integracionAG.GetFacturaPorNumeroRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetFacturaPorNumeroRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public long numero;
        
        public GetFacturaPorNumeroRequestBody() {
        }
        
        public GetFacturaPorNumeroRequestBody(string username, string password, long numero) {
            this.username = username;
            this.password = password;
            this.numero = numero;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetFacturaPorNumeroResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetFacturaPorNumeroResponse", Namespace="http://tempuri.org/", Order=0)]
        public sistemaAGP.integracionAG.GetFacturaPorNumeroResponseBody Body;
        
        public GetFacturaPorNumeroResponse() {
        }
        
        public GetFacturaPorNumeroResponse(sistemaAGP.integracionAG.GetFacturaPorNumeroResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetFacturaPorNumeroResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetFacturaPorNumeroResult;
        
        public GetFacturaPorNumeroResponseBody() {
        }
        
        public GetFacturaPorNumeroResponseBody(string GetFacturaPorNumeroResult) {
            this.GetFacturaPorNumeroResult = GetFacturaPorNumeroResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetFacturasPorFechasRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetFacturasPorFechas", Namespace="http://tempuri.org/", Order=0)]
        public sistemaAGP.integracionAG.GetFacturasPorFechasRequestBody Body;
        
        public GetFacturasPorFechasRequest() {
        }
        
        public GetFacturasPorFechasRequest(sistemaAGP.integracionAG.GetFacturasPorFechasRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetFacturasPorFechasRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string fechaini;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string fechafin;
        
        public GetFacturasPorFechasRequestBody() {
        }
        
        public GetFacturasPorFechasRequestBody(string username, string password, string fechaini, string fechafin) {
            this.username = username;
            this.password = password;
            this.fechaini = fechaini;
            this.fechafin = fechafin;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetFacturasPorFechasResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetFacturasPorFechasResponse", Namespace="http://tempuri.org/", Order=0)]
        public sistemaAGP.integracionAG.GetFacturasPorFechasResponseBody Body;
        
        public GetFacturasPorFechasResponse() {
        }
        
        public GetFacturasPorFechasResponse(sistemaAGP.integracionAG.GetFacturasPorFechasResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetFacturasPorFechasResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetFacturasPorFechasResult;
        
        public GetFacturasPorFechasResponseBody() {
        }
        
        public GetFacturasPorFechasResponseBody(string GetFacturasPorFechasResult) {
            this.GetFacturasPorFechasResult = GetFacturasPorFechasResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EncriptarRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Encriptar", Namespace="http://tempuri.org/", Order=0)]
        public sistemaAGP.integracionAG.EncriptarRequestBody Body;
        
        public EncriptarRequest() {
        }
        
        public EncriptarRequest(sistemaAGP.integracionAG.EncriptarRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class EncriptarRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string texto;
        
        public EncriptarRequestBody() {
        }
        
        public EncriptarRequestBody(string texto) {
            this.texto = texto;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EncriptarResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EncriptarResponse", Namespace="http://tempuri.org/", Order=0)]
        public sistemaAGP.integracionAG.EncriptarResponseBody Body;
        
        public EncriptarResponse() {
        }
        
        public EncriptarResponse(sistemaAGP.integracionAG.EncriptarResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class EncriptarResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string EncriptarResult;
        
        public EncriptarResponseBody() {
        }
        
        public EncriptarResponseBody(string EncriptarResult) {
            this.EncriptarResult = EncriptarResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WSIntegracionAGPSoapChannel : sistemaAGP.integracionAG.WSIntegracionAGPSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WSIntegracionAGPSoapClient : System.ServiceModel.ClientBase<sistemaAGP.integracionAG.WSIntegracionAGPSoap>, sistemaAGP.integracionAG.WSIntegracionAGPSoap {
        
        public WSIntegracionAGPSoapClient() {
        }
        
        public WSIntegracionAGPSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WSIntegracionAGPSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSIntegracionAGPSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSIntegracionAGPSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        sistemaAGP.integracionAG.GetFacturaPorNumeroResponse sistemaAGP.integracionAG.WSIntegracionAGPSoap.GetFacturaPorNumero(sistemaAGP.integracionAG.GetFacturaPorNumeroRequest request) {
            return base.Channel.GetFacturaPorNumero(request);
        }
        
        public string GetFacturaPorNumero(string username, string password, long numero) {
            sistemaAGP.integracionAG.GetFacturaPorNumeroRequest inValue = new sistemaAGP.integracionAG.GetFacturaPorNumeroRequest();
            inValue.Body = new sistemaAGP.integracionAG.GetFacturaPorNumeroRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            inValue.Body.numero = numero;
            sistemaAGP.integracionAG.GetFacturaPorNumeroResponse retVal = ((sistemaAGP.integracionAG.WSIntegracionAGPSoap)(this)).GetFacturaPorNumero(inValue);
            return retVal.Body.GetFacturaPorNumeroResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        sistemaAGP.integracionAG.GetFacturasPorFechasResponse sistemaAGP.integracionAG.WSIntegracionAGPSoap.GetFacturasPorFechas(sistemaAGP.integracionAG.GetFacturasPorFechasRequest request) {
            return base.Channel.GetFacturasPorFechas(request);
        }
        
        public string GetFacturasPorFechas(string username, string password, string fechaini, string fechafin) {
            sistemaAGP.integracionAG.GetFacturasPorFechasRequest inValue = new sistemaAGP.integracionAG.GetFacturasPorFechasRequest();
            inValue.Body = new sistemaAGP.integracionAG.GetFacturasPorFechasRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            inValue.Body.fechaini = fechaini;
            inValue.Body.fechafin = fechafin;
            sistemaAGP.integracionAG.GetFacturasPorFechasResponse retVal = ((sistemaAGP.integracionAG.WSIntegracionAGPSoap)(this)).GetFacturasPorFechas(inValue);
            return retVal.Body.GetFacturasPorFechasResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        sistemaAGP.integracionAG.EncriptarResponse sistemaAGP.integracionAG.WSIntegracionAGPSoap.Encriptar(sistemaAGP.integracionAG.EncriptarRequest request) {
            return base.Channel.Encriptar(request);
        }
        
        public string Encriptar(string texto) {
            sistemaAGP.integracionAG.EncriptarRequest inValue = new sistemaAGP.integracionAG.EncriptarRequest();
            inValue.Body = new sistemaAGP.integracionAG.EncriptarRequestBody();
            inValue.Body.texto = texto;
            sistemaAGP.integracionAG.EncriptarResponse retVal = ((sistemaAGP.integracionAG.WSIntegracionAGPSoap)(this)).Encriptar(inValue);
            return retVal.Body.EncriptarResult;
        }
    }
}
