//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sistemaAGP.AgNotaPedido {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="NotaPedidoBE", Namespace="http://schemas.datacontract.org/2004/07/Gildemeister.WCF.BE.NotaPedido")]
    [System.SerializableAttribute()]
    public partial class NotaPedidoBE : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int codigoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string msg_ErrorField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int codigo {
            get {
                return this.codigoField;
            }
            set {
                if ((this.codigoField.Equals(value) != true)) {
                    this.codigoField = value;
                    this.RaisePropertyChanged("codigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string msg_Error {
            get {
                return this.msg_ErrorField;
            }
            set {
                if ((object.ReferenceEquals(this.msg_ErrorField, value) != true)) {
                    this.msg_ErrorField = value;
                    this.RaisePropertyChanged("msg_Error");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://Minvestgroup.com", ConfigurationName="AgNotaPedido.INotaPedidoService")]
    public interface INotaPedidoService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Minvestgroup.com/INotaPedidoService/RegistraNotaPedido", ReplyAction="http://Minvestgroup.com/INotaPedidoService/RegistraNotaPedidoResponse")]
        sistemaAGP.AgNotaPedido.NotaPedidoBE RegistraNotaPedido(string nro_ordenVenta, string nro_vin, string nu_rut_solicitante);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Minvestgroup.com/INotaPedidoService/ActualizaEstadoNotaPedido", ReplyAction="http://Minvestgroup.com/INotaPedidoService/ActualizaEstadoNotaPedidoResponse")]
        int ActualizaEstadoNotaPedido(string nro_vin, string estado);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface INotaPedidoServiceChannel : sistemaAGP.AgNotaPedido.INotaPedidoService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class NotaPedidoServiceClient : System.ServiceModel.ClientBase<sistemaAGP.AgNotaPedido.INotaPedidoService>, sistemaAGP.AgNotaPedido.INotaPedidoService {
        
        public NotaPedidoServiceClient() {
        }
        
        public NotaPedidoServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public NotaPedidoServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NotaPedidoServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NotaPedidoServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public sistemaAGP.AgNotaPedido.NotaPedidoBE RegistraNotaPedido(string nro_ordenVenta, string nro_vin, string nu_rut_solicitante) {
            return base.Channel.RegistraNotaPedido(nro_ordenVenta, nro_vin, nu_rut_solicitante);
        }
        
        public int ActualizaEstadoNotaPedido(string nro_vin, string estado) {
            return base.Channel.ActualizaEstadoNotaPedido(nro_vin, estado);
        }
    }
}
