//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sistemaAGP.IntegracionMarubeni {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="IntegracionMarubeni.Service1Soap")]
    public interface Service1Soap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Auto_Mae_AdquirienteAGPView", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet Auto_Mae_AdquirienteAGPView(int RutEmpresaCD, string Usr_id, string Password, string NumeroDocumento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Auto_Mae_CompraParaAGPView", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet Auto_Mae_CompraParaAGPView(int RutEmpresaCD, string Usr_id, string Password, string NumeroDocumento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Auto_Mae_DatosVehiculosAGPView", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet Auto_Mae_DatosVehiculosAGPView(int RutEmpresaCD, string Usr_id, string Password, string NumeroDocumento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Auto_Mae_FacturasAGPView", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet Auto_Mae_FacturasAGPView(int RutEmpresaCD, string Usr_id, string Password, string NumeroDocumento);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface Service1SoapChannel : sistemaAGP.IntegracionMarubeni.Service1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1SoapClient : System.ServiceModel.ClientBase<sistemaAGP.IntegracionMarubeni.Service1Soap>, sistemaAGP.IntegracionMarubeni.Service1Soap {
        
        public Service1SoapClient() {
        }
        
        public Service1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataSet Auto_Mae_AdquirienteAGPView(int RutEmpresaCD, string Usr_id, string Password, string NumeroDocumento) {
            return base.Channel.Auto_Mae_AdquirienteAGPView(RutEmpresaCD, Usr_id, Password, NumeroDocumento);
        }
        
        public System.Data.DataSet Auto_Mae_CompraParaAGPView(int RutEmpresaCD, string Usr_id, string Password, string NumeroDocumento) {
            return base.Channel.Auto_Mae_CompraParaAGPView(RutEmpresaCD, Usr_id, Password, NumeroDocumento);
        }
        
        public System.Data.DataSet Auto_Mae_DatosVehiculosAGPView(int RutEmpresaCD, string Usr_id, string Password, string NumeroDocumento) {
            return base.Channel.Auto_Mae_DatosVehiculosAGPView(RutEmpresaCD, Usr_id, Password, NumeroDocumento);
        }
        
        public System.Data.DataSet Auto_Mae_FacturasAGPView(int RutEmpresaCD, string Usr_id, string Password, string NumeroDocumento) {
            return base.Channel.Auto_Mae_FacturasAGPView(RutEmpresaCD, Usr_id, Password, NumeroDocumento);
        }
    }
}
