//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sistemaAGP.WSPeru {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TX_DATO_GENERAL_NOTA_PEDIDO", Namespace="http://schemas.datacontract.org/2004/07/WSIntegracionAGPPeru")]
    [System.SerializableAttribute()]
    public partial class TX_DATO_GENERAL_NOTA_PEDIDO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NUMERO_NOTA_PEDIDOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NOMBRESField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string APELLIDO_PATERNOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string APELLIDO_MATERNOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DOMICILIOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TIPO_DOCUMENTO_IDENTIDADField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NRO_DOCUMENTO_IDENTIDADField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ESTADO_CIVILField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NOMBRES_CONYUGEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TIPO_DOCUMENTO_IDENTIDAD_CONYUGEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NRO_DOCUMENTO_IDENTIDAD_CONYUGEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RAZON_SOCIALField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string INSCRIPCION_REGISTRALField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DOMICILIO_RAZON_SOCIALField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string REPRESENTANTE_LEGALField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TIPO_DOCUMENTO_IDENTIDAD_REP_LEGALField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NRO_DOCUMENTO_IDENTIDAD_REP_LEGALField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NUMERO_VINField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NUMERO_SERIE_VINField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MARCAField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MODELOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VERSIONField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string A_MODELOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string A_FABRICACIONField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CLASE_CARROCERIAField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CARROCERIAField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string COLORField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NUMERO_MOTORField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string POTENCIA_MOTORField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string COMBUSTIBLEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CILINDROSField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CILINDRADAField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LONGITUDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NUMERO_PASAJEROSField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PESO_NETOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CARGA_UTILField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PESO_BRUTOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NUMERO_ASIENTOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NUMERO_EJESField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ANCHOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NUMERO_PUERTASField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ALTOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NUMERO_RUEDASField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FORMULA_RODANTEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NUMERO_DOCUMENTO_VENTAField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FECHA_EMISION_DOC_VENTAField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal MONTO_TOTAL_VEHICULOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TIPO_MONEDAField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CATEGORIA_MTCField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string USO_MTCField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CUSR_ID_USUARIO_CREACIONField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FECHA_CREACIONField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CUSR_ID_USUARIO_ULTIMA_MODIFICACIONField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> FECHA_MODIFICACIONField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IP_CREACIONField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IP_MODIFICACIONField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ASESOR_COMERCIALField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ADMINISTRADOR_VENTAField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FORMA_PAGOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string APELLIDO_PATERNO_CONYUGEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string APELLIDO_MATERNO_CONYUGEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CODIGO_DEPARTAMENTOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DEPARTAMENTOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CODIGO_PROVINCIAField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PROVINCIAField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CODIGO_DISTRITOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DISTRITOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private sistemaAGP.WSPeru.TX_INFORMACION_RETORNO[] TX_INFORMACION_RETORNOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private sistemaAGP.WSPeru.TX_DETALLE_FORMA_PAGO[] TX_DETALLE_FORMA_PAGOField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NUMERO_NOTA_PEDIDO {
            get {
                return this.NUMERO_NOTA_PEDIDOField;
            }
            set {
                if ((object.ReferenceEquals(this.NUMERO_NOTA_PEDIDOField, value) != true)) {
                    this.NUMERO_NOTA_PEDIDOField = value;
                    this.RaisePropertyChanged("NUMERO_NOTA_PEDIDO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public string NOMBRES {
            get {
                return this.NOMBRESField;
            }
            set {
                if ((object.ReferenceEquals(this.NOMBRESField, value) != true)) {
                    this.NOMBRESField = value;
                    this.RaisePropertyChanged("NOMBRES");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public string APELLIDO_PATERNO {
            get {
                return this.APELLIDO_PATERNOField;
            }
            set {
                if ((object.ReferenceEquals(this.APELLIDO_PATERNOField, value) != true)) {
                    this.APELLIDO_PATERNOField = value;
                    this.RaisePropertyChanged("APELLIDO_PATERNO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public string APELLIDO_MATERNO {
            get {
                return this.APELLIDO_MATERNOField;
            }
            set {
                if ((object.ReferenceEquals(this.APELLIDO_MATERNOField, value) != true)) {
                    this.APELLIDO_MATERNOField = value;
                    this.RaisePropertyChanged("APELLIDO_MATERNO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public string DOMICILIO {
            get {
                return this.DOMICILIOField;
            }
            set {
                if ((object.ReferenceEquals(this.DOMICILIOField, value) != true)) {
                    this.DOMICILIOField = value;
                    this.RaisePropertyChanged("DOMICILIO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public string TIPO_DOCUMENTO_IDENTIDAD {
            get {
                return this.TIPO_DOCUMENTO_IDENTIDADField;
            }
            set {
                if ((object.ReferenceEquals(this.TIPO_DOCUMENTO_IDENTIDADField, value) != true)) {
                    this.TIPO_DOCUMENTO_IDENTIDADField = value;
                    this.RaisePropertyChanged("TIPO_DOCUMENTO_IDENTIDAD");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public string NRO_DOCUMENTO_IDENTIDAD {
            get {
                return this.NRO_DOCUMENTO_IDENTIDADField;
            }
            set {
                if ((object.ReferenceEquals(this.NRO_DOCUMENTO_IDENTIDADField, value) != true)) {
                    this.NRO_DOCUMENTO_IDENTIDADField = value;
                    this.RaisePropertyChanged("NRO_DOCUMENTO_IDENTIDAD");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=7)]
        public string ESTADO_CIVIL {
            get {
                return this.ESTADO_CIVILField;
            }
            set {
                if ((object.ReferenceEquals(this.ESTADO_CIVILField, value) != true)) {
                    this.ESTADO_CIVILField = value;
                    this.RaisePropertyChanged("ESTADO_CIVIL");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=8)]
        public string NOMBRES_CONYUGE {
            get {
                return this.NOMBRES_CONYUGEField;
            }
            set {
                if ((object.ReferenceEquals(this.NOMBRES_CONYUGEField, value) != true)) {
                    this.NOMBRES_CONYUGEField = value;
                    this.RaisePropertyChanged("NOMBRES_CONYUGE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=9)]
        public string TIPO_DOCUMENTO_IDENTIDAD_CONYUGE {
            get {
                return this.TIPO_DOCUMENTO_IDENTIDAD_CONYUGEField;
            }
            set {
                if ((object.ReferenceEquals(this.TIPO_DOCUMENTO_IDENTIDAD_CONYUGEField, value) != true)) {
                    this.TIPO_DOCUMENTO_IDENTIDAD_CONYUGEField = value;
                    this.RaisePropertyChanged("TIPO_DOCUMENTO_IDENTIDAD_CONYUGE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=10)]
        public string NRO_DOCUMENTO_IDENTIDAD_CONYUGE {
            get {
                return this.NRO_DOCUMENTO_IDENTIDAD_CONYUGEField;
            }
            set {
                if ((object.ReferenceEquals(this.NRO_DOCUMENTO_IDENTIDAD_CONYUGEField, value) != true)) {
                    this.NRO_DOCUMENTO_IDENTIDAD_CONYUGEField = value;
                    this.RaisePropertyChanged("NRO_DOCUMENTO_IDENTIDAD_CONYUGE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=11)]
        public string RAZON_SOCIAL {
            get {
                return this.RAZON_SOCIALField;
            }
            set {
                if ((object.ReferenceEquals(this.RAZON_SOCIALField, value) != true)) {
                    this.RAZON_SOCIALField = value;
                    this.RaisePropertyChanged("RAZON_SOCIAL");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=12)]
        public string INSCRIPCION_REGISTRAL {
            get {
                return this.INSCRIPCION_REGISTRALField;
            }
            set {
                if ((object.ReferenceEquals(this.INSCRIPCION_REGISTRALField, value) != true)) {
                    this.INSCRIPCION_REGISTRALField = value;
                    this.RaisePropertyChanged("INSCRIPCION_REGISTRAL");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=13)]
        public string DOMICILIO_RAZON_SOCIAL {
            get {
                return this.DOMICILIO_RAZON_SOCIALField;
            }
            set {
                if ((object.ReferenceEquals(this.DOMICILIO_RAZON_SOCIALField, value) != true)) {
                    this.DOMICILIO_RAZON_SOCIALField = value;
                    this.RaisePropertyChanged("DOMICILIO_RAZON_SOCIAL");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=14)]
        public string REPRESENTANTE_LEGAL {
            get {
                return this.REPRESENTANTE_LEGALField;
            }
            set {
                if ((object.ReferenceEquals(this.REPRESENTANTE_LEGALField, value) != true)) {
                    this.REPRESENTANTE_LEGALField = value;
                    this.RaisePropertyChanged("REPRESENTANTE_LEGAL");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=15)]
        public string TIPO_DOCUMENTO_IDENTIDAD_REP_LEGAL {
            get {
                return this.TIPO_DOCUMENTO_IDENTIDAD_REP_LEGALField;
            }
            set {
                if ((object.ReferenceEquals(this.TIPO_DOCUMENTO_IDENTIDAD_REP_LEGALField, value) != true)) {
                    this.TIPO_DOCUMENTO_IDENTIDAD_REP_LEGALField = value;
                    this.RaisePropertyChanged("TIPO_DOCUMENTO_IDENTIDAD_REP_LEGAL");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=16)]
        public string NRO_DOCUMENTO_IDENTIDAD_REP_LEGAL {
            get {
                return this.NRO_DOCUMENTO_IDENTIDAD_REP_LEGALField;
            }
            set {
                if ((object.ReferenceEquals(this.NRO_DOCUMENTO_IDENTIDAD_REP_LEGALField, value) != true)) {
                    this.NRO_DOCUMENTO_IDENTIDAD_REP_LEGALField = value;
                    this.RaisePropertyChanged("NRO_DOCUMENTO_IDENTIDAD_REP_LEGAL");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=17)]
        public string NUMERO_VIN {
            get {
                return this.NUMERO_VINField;
            }
            set {
                if ((object.ReferenceEquals(this.NUMERO_VINField, value) != true)) {
                    this.NUMERO_VINField = value;
                    this.RaisePropertyChanged("NUMERO_VIN");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=18)]
        public string NUMERO_SERIE_VIN {
            get {
                return this.NUMERO_SERIE_VINField;
            }
            set {
                if ((object.ReferenceEquals(this.NUMERO_SERIE_VINField, value) != true)) {
                    this.NUMERO_SERIE_VINField = value;
                    this.RaisePropertyChanged("NUMERO_SERIE_VIN");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=19)]
        public string MARCA {
            get {
                return this.MARCAField;
            }
            set {
                if ((object.ReferenceEquals(this.MARCAField, value) != true)) {
                    this.MARCAField = value;
                    this.RaisePropertyChanged("MARCA");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=20)]
        public string MODELO {
            get {
                return this.MODELOField;
            }
            set {
                if ((object.ReferenceEquals(this.MODELOField, value) != true)) {
                    this.MODELOField = value;
                    this.RaisePropertyChanged("MODELO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=21)]
        public string VERSION {
            get {
                return this.VERSIONField;
            }
            set {
                if ((object.ReferenceEquals(this.VERSIONField, value) != true)) {
                    this.VERSIONField = value;
                    this.RaisePropertyChanged("VERSION");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=22)]
        public string A_MODELO {
            get {
                return this.A_MODELOField;
            }
            set {
                if ((object.ReferenceEquals(this.A_MODELOField, value) != true)) {
                    this.A_MODELOField = value;
                    this.RaisePropertyChanged("A_MODELO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=23)]
        public string A_FABRICACION {
            get {
                return this.A_FABRICACIONField;
            }
            set {
                if ((object.ReferenceEquals(this.A_FABRICACIONField, value) != true)) {
                    this.A_FABRICACIONField = value;
                    this.RaisePropertyChanged("A_FABRICACION");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=24)]
        public string CLASE_CARROCERIA {
            get {
                return this.CLASE_CARROCERIAField;
            }
            set {
                if ((object.ReferenceEquals(this.CLASE_CARROCERIAField, value) != true)) {
                    this.CLASE_CARROCERIAField = value;
                    this.RaisePropertyChanged("CLASE_CARROCERIA");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=25)]
        public string CARROCERIA {
            get {
                return this.CARROCERIAField;
            }
            set {
                if ((object.ReferenceEquals(this.CARROCERIAField, value) != true)) {
                    this.CARROCERIAField = value;
                    this.RaisePropertyChanged("CARROCERIA");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=26)]
        public string COLOR {
            get {
                return this.COLORField;
            }
            set {
                if ((object.ReferenceEquals(this.COLORField, value) != true)) {
                    this.COLORField = value;
                    this.RaisePropertyChanged("COLOR");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=27)]
        public string NUMERO_MOTOR {
            get {
                return this.NUMERO_MOTORField;
            }
            set {
                if ((object.ReferenceEquals(this.NUMERO_MOTORField, value) != true)) {
                    this.NUMERO_MOTORField = value;
                    this.RaisePropertyChanged("NUMERO_MOTOR");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=28)]
        public string POTENCIA_MOTOR {
            get {
                return this.POTENCIA_MOTORField;
            }
            set {
                if ((object.ReferenceEquals(this.POTENCIA_MOTORField, value) != true)) {
                    this.POTENCIA_MOTORField = value;
                    this.RaisePropertyChanged("POTENCIA_MOTOR");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=29)]
        public string COMBUSTIBLE {
            get {
                return this.COMBUSTIBLEField;
            }
            set {
                if ((object.ReferenceEquals(this.COMBUSTIBLEField, value) != true)) {
                    this.COMBUSTIBLEField = value;
                    this.RaisePropertyChanged("COMBUSTIBLE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=30)]
        public string CILINDROS {
            get {
                return this.CILINDROSField;
            }
            set {
                if ((object.ReferenceEquals(this.CILINDROSField, value) != true)) {
                    this.CILINDROSField = value;
                    this.RaisePropertyChanged("CILINDROS");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=31)]
        public string CILINDRADA {
            get {
                return this.CILINDRADAField;
            }
            set {
                if ((object.ReferenceEquals(this.CILINDRADAField, value) != true)) {
                    this.CILINDRADAField = value;
                    this.RaisePropertyChanged("CILINDRADA");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=32)]
        public string LONGITUD {
            get {
                return this.LONGITUDField;
            }
            set {
                if ((object.ReferenceEquals(this.LONGITUDField, value) != true)) {
                    this.LONGITUDField = value;
                    this.RaisePropertyChanged("LONGITUD");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=33)]
        public string NUMERO_PASAJEROS {
            get {
                return this.NUMERO_PASAJEROSField;
            }
            set {
                if ((object.ReferenceEquals(this.NUMERO_PASAJEROSField, value) != true)) {
                    this.NUMERO_PASAJEROSField = value;
                    this.RaisePropertyChanged("NUMERO_PASAJEROS");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=34)]
        public string PESO_NETO {
            get {
                return this.PESO_NETOField;
            }
            set {
                if ((object.ReferenceEquals(this.PESO_NETOField, value) != true)) {
                    this.PESO_NETOField = value;
                    this.RaisePropertyChanged("PESO_NETO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=35)]
        public string CARGA_UTIL {
            get {
                return this.CARGA_UTILField;
            }
            set {
                if ((object.ReferenceEquals(this.CARGA_UTILField, value) != true)) {
                    this.CARGA_UTILField = value;
                    this.RaisePropertyChanged("CARGA_UTIL");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=36)]
        public string PESO_BRUTO {
            get {
                return this.PESO_BRUTOField;
            }
            set {
                if ((object.ReferenceEquals(this.PESO_BRUTOField, value) != true)) {
                    this.PESO_BRUTOField = value;
                    this.RaisePropertyChanged("PESO_BRUTO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=37)]
        public string NUMERO_ASIENTO {
            get {
                return this.NUMERO_ASIENTOField;
            }
            set {
                if ((object.ReferenceEquals(this.NUMERO_ASIENTOField, value) != true)) {
                    this.NUMERO_ASIENTOField = value;
                    this.RaisePropertyChanged("NUMERO_ASIENTO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=38)]
        public string NUMERO_EJES {
            get {
                return this.NUMERO_EJESField;
            }
            set {
                if ((object.ReferenceEquals(this.NUMERO_EJESField, value) != true)) {
                    this.NUMERO_EJESField = value;
                    this.RaisePropertyChanged("NUMERO_EJES");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=39)]
        public string ANCHO {
            get {
                return this.ANCHOField;
            }
            set {
                if ((object.ReferenceEquals(this.ANCHOField, value) != true)) {
                    this.ANCHOField = value;
                    this.RaisePropertyChanged("ANCHO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=40)]
        public string NUMERO_PUERTAS {
            get {
                return this.NUMERO_PUERTASField;
            }
            set {
                if ((object.ReferenceEquals(this.NUMERO_PUERTASField, value) != true)) {
                    this.NUMERO_PUERTASField = value;
                    this.RaisePropertyChanged("NUMERO_PUERTAS");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=41)]
        public string ALTO {
            get {
                return this.ALTOField;
            }
            set {
                if ((object.ReferenceEquals(this.ALTOField, value) != true)) {
                    this.ALTOField = value;
                    this.RaisePropertyChanged("ALTO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=42)]
        public string NUMERO_RUEDAS {
            get {
                return this.NUMERO_RUEDASField;
            }
            set {
                if ((object.ReferenceEquals(this.NUMERO_RUEDASField, value) != true)) {
                    this.NUMERO_RUEDASField = value;
                    this.RaisePropertyChanged("NUMERO_RUEDAS");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=43)]
        public string FORMULA_RODANTE {
            get {
                return this.FORMULA_RODANTEField;
            }
            set {
                if ((object.ReferenceEquals(this.FORMULA_RODANTEField, value) != true)) {
                    this.FORMULA_RODANTEField = value;
                    this.RaisePropertyChanged("FORMULA_RODANTE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=44)]
        public string NUMERO_DOCUMENTO_VENTA {
            get {
                return this.NUMERO_DOCUMENTO_VENTAField;
            }
            set {
                if ((object.ReferenceEquals(this.NUMERO_DOCUMENTO_VENTAField, value) != true)) {
                    this.NUMERO_DOCUMENTO_VENTAField = value;
                    this.RaisePropertyChanged("NUMERO_DOCUMENTO_VENTA");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=45)]
        public System.DateTime FECHA_EMISION_DOC_VENTA {
            get {
                return this.FECHA_EMISION_DOC_VENTAField;
            }
            set {
                if ((this.FECHA_EMISION_DOC_VENTAField.Equals(value) != true)) {
                    this.FECHA_EMISION_DOC_VENTAField = value;
                    this.RaisePropertyChanged("FECHA_EMISION_DOC_VENTA");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=46)]
        public decimal MONTO_TOTAL_VEHICULO {
            get {
                return this.MONTO_TOTAL_VEHICULOField;
            }
            set {
                if ((this.MONTO_TOTAL_VEHICULOField.Equals(value) != true)) {
                    this.MONTO_TOTAL_VEHICULOField = value;
                    this.RaisePropertyChanged("MONTO_TOTAL_VEHICULO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=47)]
        public string TIPO_MONEDA {
            get {
                return this.TIPO_MONEDAField;
            }
            set {
                if ((object.ReferenceEquals(this.TIPO_MONEDAField, value) != true)) {
                    this.TIPO_MONEDAField = value;
                    this.RaisePropertyChanged("TIPO_MONEDA");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=48)]
        public string CATEGORIA_MTC {
            get {
                return this.CATEGORIA_MTCField;
            }
            set {
                if ((object.ReferenceEquals(this.CATEGORIA_MTCField, value) != true)) {
                    this.CATEGORIA_MTCField = value;
                    this.RaisePropertyChanged("CATEGORIA_MTC");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=49)]
        public string USO_MTC {
            get {
                return this.USO_MTCField;
            }
            set {
                if ((object.ReferenceEquals(this.USO_MTCField, value) != true)) {
                    this.USO_MTCField = value;
                    this.RaisePropertyChanged("USO_MTC");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=50)]
        public string CUSR_ID_USUARIO_CREACION {
            get {
                return this.CUSR_ID_USUARIO_CREACIONField;
            }
            set {
                if ((object.ReferenceEquals(this.CUSR_ID_USUARIO_CREACIONField, value) != true)) {
                    this.CUSR_ID_USUARIO_CREACIONField = value;
                    this.RaisePropertyChanged("CUSR_ID_USUARIO_CREACION");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=51)]
        public System.DateTime FECHA_CREACION {
            get {
                return this.FECHA_CREACIONField;
            }
            set {
                if ((this.FECHA_CREACIONField.Equals(value) != true)) {
                    this.FECHA_CREACIONField = value;
                    this.RaisePropertyChanged("FECHA_CREACION");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=52)]
        public string CUSR_ID_USUARIO_ULTIMA_MODIFICACION {
            get {
                return this.CUSR_ID_USUARIO_ULTIMA_MODIFICACIONField;
            }
            set {
                if ((object.ReferenceEquals(this.CUSR_ID_USUARIO_ULTIMA_MODIFICACIONField, value) != true)) {
                    this.CUSR_ID_USUARIO_ULTIMA_MODIFICACIONField = value;
                    this.RaisePropertyChanged("CUSR_ID_USUARIO_ULTIMA_MODIFICACION");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=53)]
        public System.Nullable<System.DateTime> FECHA_MODIFICACION {
            get {
                return this.FECHA_MODIFICACIONField;
            }
            set {
                if ((this.FECHA_MODIFICACIONField.Equals(value) != true)) {
                    this.FECHA_MODIFICACIONField = value;
                    this.RaisePropertyChanged("FECHA_MODIFICACION");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=54)]
        public string IP_CREACION {
            get {
                return this.IP_CREACIONField;
            }
            set {
                if ((object.ReferenceEquals(this.IP_CREACIONField, value) != true)) {
                    this.IP_CREACIONField = value;
                    this.RaisePropertyChanged("IP_CREACION");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=55)]
        public string IP_MODIFICACION {
            get {
                return this.IP_MODIFICACIONField;
            }
            set {
                if ((object.ReferenceEquals(this.IP_MODIFICACIONField, value) != true)) {
                    this.IP_MODIFICACIONField = value;
                    this.RaisePropertyChanged("IP_MODIFICACION");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=56)]
        public string ASESOR_COMERCIAL {
            get {
                return this.ASESOR_COMERCIALField;
            }
            set {
                if ((object.ReferenceEquals(this.ASESOR_COMERCIALField, value) != true)) {
                    this.ASESOR_COMERCIALField = value;
                    this.RaisePropertyChanged("ASESOR_COMERCIAL");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=57)]
        public string ADMINISTRADOR_VENTA {
            get {
                return this.ADMINISTRADOR_VENTAField;
            }
            set {
                if ((object.ReferenceEquals(this.ADMINISTRADOR_VENTAField, value) != true)) {
                    this.ADMINISTRADOR_VENTAField = value;
                    this.RaisePropertyChanged("ADMINISTRADOR_VENTA");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=58)]
        public string FORMA_PAGO {
            get {
                return this.FORMA_PAGOField;
            }
            set {
                if ((object.ReferenceEquals(this.FORMA_PAGOField, value) != true)) {
                    this.FORMA_PAGOField = value;
                    this.RaisePropertyChanged("FORMA_PAGO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=59)]
        public string APELLIDO_PATERNO_CONYUGE {
            get {
                return this.APELLIDO_PATERNO_CONYUGEField;
            }
            set {
                if ((object.ReferenceEquals(this.APELLIDO_PATERNO_CONYUGEField, value) != true)) {
                    this.APELLIDO_PATERNO_CONYUGEField = value;
                    this.RaisePropertyChanged("APELLIDO_PATERNO_CONYUGE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=60)]
        public string APELLIDO_MATERNO_CONYUGE {
            get {
                return this.APELLIDO_MATERNO_CONYUGEField;
            }
            set {
                if ((object.ReferenceEquals(this.APELLIDO_MATERNO_CONYUGEField, value) != true)) {
                    this.APELLIDO_MATERNO_CONYUGEField = value;
                    this.RaisePropertyChanged("APELLIDO_MATERNO_CONYUGE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=61)]
        public string CODIGO_DEPARTAMENTO {
            get {
                return this.CODIGO_DEPARTAMENTOField;
            }
            set {
                if ((object.ReferenceEquals(this.CODIGO_DEPARTAMENTOField, value) != true)) {
                    this.CODIGO_DEPARTAMENTOField = value;
                    this.RaisePropertyChanged("CODIGO_DEPARTAMENTO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=62)]
        public string DEPARTAMENTO {
            get {
                return this.DEPARTAMENTOField;
            }
            set {
                if ((object.ReferenceEquals(this.DEPARTAMENTOField, value) != true)) {
                    this.DEPARTAMENTOField = value;
                    this.RaisePropertyChanged("DEPARTAMENTO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=63)]
        public string CODIGO_PROVINCIA {
            get {
                return this.CODIGO_PROVINCIAField;
            }
            set {
                if ((object.ReferenceEquals(this.CODIGO_PROVINCIAField, value) != true)) {
                    this.CODIGO_PROVINCIAField = value;
                    this.RaisePropertyChanged("CODIGO_PROVINCIA");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=64)]
        public string PROVINCIA {
            get {
                return this.PROVINCIAField;
            }
            set {
                if ((object.ReferenceEquals(this.PROVINCIAField, value) != true)) {
                    this.PROVINCIAField = value;
                    this.RaisePropertyChanged("PROVINCIA");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=65)]
        public string CODIGO_DISTRITO {
            get {
                return this.CODIGO_DISTRITOField;
            }
            set {
                if ((object.ReferenceEquals(this.CODIGO_DISTRITOField, value) != true)) {
                    this.CODIGO_DISTRITOField = value;
                    this.RaisePropertyChanged("CODIGO_DISTRITO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=66)]
        public string DISTRITO {
            get {
                return this.DISTRITOField;
            }
            set {
                if ((object.ReferenceEquals(this.DISTRITOField, value) != true)) {
                    this.DISTRITOField = value;
                    this.RaisePropertyChanged("DISTRITO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=67)]
        public sistemaAGP.WSPeru.TX_INFORMACION_RETORNO[] TX_INFORMACION_RETORNO {
            get {
                return this.TX_INFORMACION_RETORNOField;
            }
            set {
                if ((object.ReferenceEquals(this.TX_INFORMACION_RETORNOField, value) != true)) {
                    this.TX_INFORMACION_RETORNOField = value;
                    this.RaisePropertyChanged("TX_INFORMACION_RETORNO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=68)]
        public sistemaAGP.WSPeru.TX_DETALLE_FORMA_PAGO[] TX_DETALLE_FORMA_PAGO {
            get {
                return this.TX_DETALLE_FORMA_PAGOField;
            }
            set {
                if ((object.ReferenceEquals(this.TX_DETALLE_FORMA_PAGOField, value) != true)) {
                    this.TX_DETALLE_FORMA_PAGOField = value;
                    this.RaisePropertyChanged("TX_DETALLE_FORMA_PAGO");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TX_INFORMACION_RETORNO", Namespace="http://schemas.datacontract.org/2004/07/WSIntegracionAGPPeru")]
    [System.SerializableAttribute()]
    public partial class TX_INFORMACION_RETORNO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ID_INFO_RETORNOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NUMERO_NOTA_PEDIDOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FECHA_REGISTRO_MTCField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NUMERO_PLACAField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CUSR_ID_USUARIO_CREACIONField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FECHA_CREACIONField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CUSR_ID_USUARIO_ULTIMA_MODIFICACIONField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> FECHA_MODIFICACIONField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IP_CREACIONField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IP_MODIFICACIONField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID_INFO_RETORNO {
            get {
                return this.ID_INFO_RETORNOField;
            }
            set {
                if ((this.ID_INFO_RETORNOField.Equals(value) != true)) {
                    this.ID_INFO_RETORNOField = value;
                    this.RaisePropertyChanged("ID_INFO_RETORNO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NUMERO_NOTA_PEDIDO {
            get {
                return this.NUMERO_NOTA_PEDIDOField;
            }
            set {
                if ((object.ReferenceEquals(this.NUMERO_NOTA_PEDIDOField, value) != true)) {
                    this.NUMERO_NOTA_PEDIDOField = value;
                    this.RaisePropertyChanged("NUMERO_NOTA_PEDIDO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public System.DateTime FECHA_REGISTRO_MTC {
            get {
                return this.FECHA_REGISTRO_MTCField;
            }
            set {
                if ((this.FECHA_REGISTRO_MTCField.Equals(value) != true)) {
                    this.FECHA_REGISTRO_MTCField = value;
                    this.RaisePropertyChanged("FECHA_REGISTRO_MTC");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public string NUMERO_PLACA {
            get {
                return this.NUMERO_PLACAField;
            }
            set {
                if ((object.ReferenceEquals(this.NUMERO_PLACAField, value) != true)) {
                    this.NUMERO_PLACAField = value;
                    this.RaisePropertyChanged("NUMERO_PLACA");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public string CUSR_ID_USUARIO_CREACION {
            get {
                return this.CUSR_ID_USUARIO_CREACIONField;
            }
            set {
                if ((object.ReferenceEquals(this.CUSR_ID_USUARIO_CREACIONField, value) != true)) {
                    this.CUSR_ID_USUARIO_CREACIONField = value;
                    this.RaisePropertyChanged("CUSR_ID_USUARIO_CREACION");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public System.DateTime FECHA_CREACION {
            get {
                return this.FECHA_CREACIONField;
            }
            set {
                if ((this.FECHA_CREACIONField.Equals(value) != true)) {
                    this.FECHA_CREACIONField = value;
                    this.RaisePropertyChanged("FECHA_CREACION");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public string CUSR_ID_USUARIO_ULTIMA_MODIFICACION {
            get {
                return this.CUSR_ID_USUARIO_ULTIMA_MODIFICACIONField;
            }
            set {
                if ((object.ReferenceEquals(this.CUSR_ID_USUARIO_ULTIMA_MODIFICACIONField, value) != true)) {
                    this.CUSR_ID_USUARIO_ULTIMA_MODIFICACIONField = value;
                    this.RaisePropertyChanged("CUSR_ID_USUARIO_ULTIMA_MODIFICACION");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=7)]
        public System.Nullable<System.DateTime> FECHA_MODIFICACION {
            get {
                return this.FECHA_MODIFICACIONField;
            }
            set {
                if ((this.FECHA_MODIFICACIONField.Equals(value) != true)) {
                    this.FECHA_MODIFICACIONField = value;
                    this.RaisePropertyChanged("FECHA_MODIFICACION");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=8)]
        public string IP_CREACION {
            get {
                return this.IP_CREACIONField;
            }
            set {
                if ((object.ReferenceEquals(this.IP_CREACIONField, value) != true)) {
                    this.IP_CREACIONField = value;
                    this.RaisePropertyChanged("IP_CREACION");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=9)]
        public string IP_MODIFICACION {
            get {
                return this.IP_MODIFICACIONField;
            }
            set {
                if ((object.ReferenceEquals(this.IP_MODIFICACIONField, value) != true)) {
                    this.IP_MODIFICACIONField = value;
                    this.RaisePropertyChanged("IP_MODIFICACION");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TX_DETALLE_FORMA_PAGO", Namespace="http://schemas.datacontract.org/2004/07/WSIntegracionAGPPeru")]
    [System.SerializableAttribute()]
    public partial class TX_DETALLE_FORMA_PAGO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ID_DETALLE_FORMA_PAGOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NUMERO_NOTA_PEDIDOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NUMERO_CUENTA_CORRIENTEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MEDIO_PAGOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal MONTO_ABONOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FECHA_ABONOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CUSR_ID_USUARIO_CREACIONField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FECHA_CREACIONField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CUSR_ID_USUARIO_ULTIMA_MODIFICACIONField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> FECHA_MODIFICACIONField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IP_CREACIONField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IP_MODIFICACIONField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BANCOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MONEDA_CUENTA_BANCOField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID_DETALLE_FORMA_PAGO {
            get {
                return this.ID_DETALLE_FORMA_PAGOField;
            }
            set {
                if ((this.ID_DETALLE_FORMA_PAGOField.Equals(value) != true)) {
                    this.ID_DETALLE_FORMA_PAGOField = value;
                    this.RaisePropertyChanged("ID_DETALLE_FORMA_PAGO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NUMERO_NOTA_PEDIDO {
            get {
                return this.NUMERO_NOTA_PEDIDOField;
            }
            set {
                if ((object.ReferenceEquals(this.NUMERO_NOTA_PEDIDOField, value) != true)) {
                    this.NUMERO_NOTA_PEDIDOField = value;
                    this.RaisePropertyChanged("NUMERO_NOTA_PEDIDO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public string NUMERO_CUENTA_CORRIENTE {
            get {
                return this.NUMERO_CUENTA_CORRIENTEField;
            }
            set {
                if ((object.ReferenceEquals(this.NUMERO_CUENTA_CORRIENTEField, value) != true)) {
                    this.NUMERO_CUENTA_CORRIENTEField = value;
                    this.RaisePropertyChanged("NUMERO_CUENTA_CORRIENTE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public string MEDIO_PAGO {
            get {
                return this.MEDIO_PAGOField;
            }
            set {
                if ((object.ReferenceEquals(this.MEDIO_PAGOField, value) != true)) {
                    this.MEDIO_PAGOField = value;
                    this.RaisePropertyChanged("MEDIO_PAGO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public decimal MONTO_ABONO {
            get {
                return this.MONTO_ABONOField;
            }
            set {
                if ((this.MONTO_ABONOField.Equals(value) != true)) {
                    this.MONTO_ABONOField = value;
                    this.RaisePropertyChanged("MONTO_ABONO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public System.DateTime FECHA_ABONO {
            get {
                return this.FECHA_ABONOField;
            }
            set {
                if ((this.FECHA_ABONOField.Equals(value) != true)) {
                    this.FECHA_ABONOField = value;
                    this.RaisePropertyChanged("FECHA_ABONO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public string CUSR_ID_USUARIO_CREACION {
            get {
                return this.CUSR_ID_USUARIO_CREACIONField;
            }
            set {
                if ((object.ReferenceEquals(this.CUSR_ID_USUARIO_CREACIONField, value) != true)) {
                    this.CUSR_ID_USUARIO_CREACIONField = value;
                    this.RaisePropertyChanged("CUSR_ID_USUARIO_CREACION");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=7)]
        public System.DateTime FECHA_CREACION {
            get {
                return this.FECHA_CREACIONField;
            }
            set {
                if ((this.FECHA_CREACIONField.Equals(value) != true)) {
                    this.FECHA_CREACIONField = value;
                    this.RaisePropertyChanged("FECHA_CREACION");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=8)]
        public string CUSR_ID_USUARIO_ULTIMA_MODIFICACION {
            get {
                return this.CUSR_ID_USUARIO_ULTIMA_MODIFICACIONField;
            }
            set {
                if ((object.ReferenceEquals(this.CUSR_ID_USUARIO_ULTIMA_MODIFICACIONField, value) != true)) {
                    this.CUSR_ID_USUARIO_ULTIMA_MODIFICACIONField = value;
                    this.RaisePropertyChanged("CUSR_ID_USUARIO_ULTIMA_MODIFICACION");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=9)]
        public System.Nullable<System.DateTime> FECHA_MODIFICACION {
            get {
                return this.FECHA_MODIFICACIONField;
            }
            set {
                if ((this.FECHA_MODIFICACIONField.Equals(value) != true)) {
                    this.FECHA_MODIFICACIONField = value;
                    this.RaisePropertyChanged("FECHA_MODIFICACION");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=10)]
        public string IP_CREACION {
            get {
                return this.IP_CREACIONField;
            }
            set {
                if ((object.ReferenceEquals(this.IP_CREACIONField, value) != true)) {
                    this.IP_CREACIONField = value;
                    this.RaisePropertyChanged("IP_CREACION");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=11)]
        public string IP_MODIFICACION {
            get {
                return this.IP_MODIFICACIONField;
            }
            set {
                if ((object.ReferenceEquals(this.IP_MODIFICACIONField, value) != true)) {
                    this.IP_MODIFICACIONField = value;
                    this.RaisePropertyChanged("IP_MODIFICACION");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=12)]
        public string BANCO {
            get {
                return this.BANCOField;
            }
            set {
                if ((object.ReferenceEquals(this.BANCOField, value) != true)) {
                    this.BANCOField = value;
                    this.RaisePropertyChanged("BANCO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=13)]
        public string MONEDA_CUENTA_BANCO {
            get {
                return this.MONEDA_CUENTA_BANCOField;
            }
            set {
                if ((object.ReferenceEquals(this.MONEDA_CUENTA_BANCOField, value) != true)) {
                    this.MONEDA_CUENTA_BANCOField = value;
                    this.RaisePropertyChanged("MONEDA_CUENTA_BANCO");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WSPeru.IServiceIntegracion")]
    public interface IServiceIntegracion {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceIntegracion/GetNotaVenta", ReplyAction="http://tempuri.org/IServiceIntegracion/GetNotaVentaResponse")]
        sistemaAGP.WSPeru.TX_DATO_GENERAL_NOTA_PEDIDO GetNotaVenta(string user, string pass, string notaVenta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceIntegracion/SetInformacionRetorno", ReplyAction="http://tempuri.org/IServiceIntegracion/SetInformacionRetornoResponse")]
        bool SetInformacionRetorno(string user, string pass, string notaVenta, string fechaRegistro, string numeroPlaca, string usuario, string fecha, string ip);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceIntegracion/Encriptar", ReplyAction="http://tempuri.org/IServiceIntegracion/EncriptarResponse")]
        string Encriptar(string value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceIntegracion/ListaBancos", ReplyAction="http://tempuri.org/IServiceIntegracion/ListaBancosResponse")]
        string[] ListaBancos(string user, string pass);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceIntegracion/ListaMonedas", ReplyAction="http://tempuri.org/IServiceIntegracion/ListaMonedasResponse")]
        string[] ListaMonedas(string user, string pass);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceIntegracionChannel : sistemaAGP.WSPeru.IServiceIntegracion, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceIntegracionClient : System.ServiceModel.ClientBase<sistemaAGP.WSPeru.IServiceIntegracion>, sistemaAGP.WSPeru.IServiceIntegracion {
        
        public ServiceIntegracionClient() {
        }
        
        public ServiceIntegracionClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceIntegracionClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceIntegracionClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceIntegracionClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public sistemaAGP.WSPeru.TX_DATO_GENERAL_NOTA_PEDIDO GetNotaVenta(string user, string pass, string notaVenta) {
            return base.Channel.GetNotaVenta(user, pass, notaVenta);
        }
        
        public bool SetInformacionRetorno(string user, string pass, string notaVenta, string fechaRegistro, string numeroPlaca, string usuario, string fecha, string ip) {
            return base.Channel.SetInformacionRetorno(user, pass, notaVenta, fechaRegistro, numeroPlaca, usuario, fecha, ip);
        }
        
        public string Encriptar(string value) {
            return base.Channel.Encriptar(value);
        }
        
        public string[] ListaBancos(string user, string pass) {
            return base.Channel.ListaBancos(user, pass);
        }
        
        public string[] ListaMonedas(string user, string pass) {
            return base.Channel.ListaMonedas(user, pass);
        }
    }
}
