//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sistemaAGP.IntegracionProvidencia {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Pago", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Pago : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string placaField;
        
        private int total_pagoField;
        
        private System.DateTime fecha_pagoField;
        
        private int IdOperacionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string placa {
            get {
                return this.placaField;
            }
            set {
                if ((object.ReferenceEquals(this.placaField, value) != true)) {
                    this.placaField = value;
                    this.RaisePropertyChanged("placa");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int total_pago {
            get {
                return this.total_pagoField;
            }
            set {
                if ((this.total_pagoField.Equals(value) != true)) {
                    this.total_pagoField = value;
                    this.RaisePropertyChanged("total_pago");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public System.DateTime fecha_pago {
            get {
                return this.fecha_pagoField;
            }
            set {
                if ((this.fecha_pagoField.Equals(value) != true)) {
                    this.fecha_pagoField = value;
                    this.RaisePropertyChanged("fecha_pago");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public int IdOperacion {
            get {
                return this.IdOperacionField;
            }
            set {
                if ((this.IdOperacionField.Equals(value) != true)) {
                    this.IdOperacionField = value;
                    this.RaisePropertyChanged("IdOperacion");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="IntegracionProvidencia.svrAgpSoap")]
    public interface svrAgpSoap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento placa del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getPagoByPlaca", ReplyAction="*")]
        sistemaAGP.IntegracionProvidencia.getPagoByPlacaResponse getPagoByPlaca(sistemaAGP.IntegracionProvidencia.getPagoByPlacaRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento getPagoByOperacionResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getPagoByOperacion", ReplyAction="*")]
        sistemaAGP.IntegracionProvidencia.getPagoByOperacionResponse getPagoByOperacion(sistemaAGP.IntegracionProvidencia.getPagoByOperacionRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento getPagoByFechaResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getPagoByFecha", ReplyAction="*")]
        sistemaAGP.IntegracionProvidencia.getPagoByFechaResponse getPagoByFecha(sistemaAGP.IntegracionProvidencia.getPagoByFechaRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento placa del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getEmitidoByPlaca", ReplyAction="*")]
        sistemaAGP.IntegracionProvidencia.getEmitidoByPlacaResponse getEmitidoByPlaca(sistemaAGP.IntegracionProvidencia.getEmitidoByPlacaRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento getEmitidoByOperacionResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getEmitidoByOperacion", ReplyAction="*")]
        sistemaAGP.IntegracionProvidencia.getEmitidoByOperacionResponse getEmitidoByOperacion(sistemaAGP.IntegracionProvidencia.getEmitidoByOperacionRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento getEmitidoByFechaResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getEmitidoByFecha", ReplyAction="*")]
        sistemaAGP.IntegracionProvidencia.getEmitidoByFechaResponse getEmitidoByFecha(sistemaAGP.IntegracionProvidencia.getEmitidoByFechaRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getPagoByPlacaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getPagoByPlaca", Namespace="http://tempuri.org/", Order=0)]
        public sistemaAGP.IntegracionProvidencia.getPagoByPlacaRequestBody Body;
        
        public getPagoByPlacaRequest() {
        }
        
        public getPagoByPlacaRequest(sistemaAGP.IntegracionProvidencia.getPagoByPlacaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getPagoByPlacaRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string placa;
        
        public getPagoByPlacaRequestBody() {
        }
        
        public getPagoByPlacaRequestBody(string placa) {
            this.placa = placa;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getPagoByPlacaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getPagoByPlacaResponse", Namespace="http://tempuri.org/", Order=0)]
        public sistemaAGP.IntegracionProvidencia.getPagoByPlacaResponseBody Body;
        
        public getPagoByPlacaResponse() {
        }
        
        public getPagoByPlacaResponse(sistemaAGP.IntegracionProvidencia.getPagoByPlacaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getPagoByPlacaResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public sistemaAGP.IntegracionProvidencia.Pago getPagoByPlacaResult;
        
        public getPagoByPlacaResponseBody() {
        }
        
        public getPagoByPlacaResponseBody(sistemaAGP.IntegracionProvidencia.Pago getPagoByPlacaResult) {
            this.getPagoByPlacaResult = getPagoByPlacaResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getPagoByOperacionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getPagoByOperacion", Namespace="http://tempuri.org/", Order=0)]
        public sistemaAGP.IntegracionProvidencia.getPagoByOperacionRequestBody Body;
        
        public getPagoByOperacionRequest() {
        }
        
        public getPagoByOperacionRequest(sistemaAGP.IntegracionProvidencia.getPagoByOperacionRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getPagoByOperacionRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int IdOperacion;
        
        public getPagoByOperacionRequestBody() {
        }
        
        public getPagoByOperacionRequestBody(int IdOperacion) {
            this.IdOperacion = IdOperacion;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getPagoByOperacionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getPagoByOperacionResponse", Namespace="http://tempuri.org/", Order=0)]
        public sistemaAGP.IntegracionProvidencia.getPagoByOperacionResponseBody Body;
        
        public getPagoByOperacionResponse() {
        }
        
        public getPagoByOperacionResponse(sistemaAGP.IntegracionProvidencia.getPagoByOperacionResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getPagoByOperacionResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public sistemaAGP.IntegracionProvidencia.Pago getPagoByOperacionResult;
        
        public getPagoByOperacionResponseBody() {
        }
        
        public getPagoByOperacionResponseBody(sistemaAGP.IntegracionProvidencia.Pago getPagoByOperacionResult) {
            this.getPagoByOperacionResult = getPagoByOperacionResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getPagoByFechaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getPagoByFecha", Namespace="http://tempuri.org/", Order=0)]
        public sistemaAGP.IntegracionProvidencia.getPagoByFechaRequestBody Body;
        
        public getPagoByFechaRequest() {
        }
        
        public getPagoByFechaRequest(sistemaAGP.IntegracionProvidencia.getPagoByFechaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getPagoByFechaRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public System.DateTime FecPagoDesde;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public System.DateTime FecPagoHasta;
        
        public getPagoByFechaRequestBody() {
        }
        
        public getPagoByFechaRequestBody(System.DateTime FecPagoDesde, System.DateTime FecPagoHasta) {
            this.FecPagoDesde = FecPagoDesde;
            this.FecPagoHasta = FecPagoHasta;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getPagoByFechaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getPagoByFechaResponse", Namespace="http://tempuri.org/", Order=0)]
        public sistemaAGP.IntegracionProvidencia.getPagoByFechaResponseBody Body;
        
        public getPagoByFechaResponse() {
        }
        
        public getPagoByFechaResponse(sistemaAGP.IntegracionProvidencia.getPagoByFechaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getPagoByFechaResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public sistemaAGP.IntegracionProvidencia.Pago[] getPagoByFechaResult;
        
        public getPagoByFechaResponseBody() {
        }
        
        public getPagoByFechaResponseBody(sistemaAGP.IntegracionProvidencia.Pago[] getPagoByFechaResult) {
            this.getPagoByFechaResult = getPagoByFechaResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getEmitidoByPlacaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getEmitidoByPlaca", Namespace="http://tempuri.org/", Order=0)]
        public sistemaAGP.IntegracionProvidencia.getEmitidoByPlacaRequestBody Body;
        
        public getEmitidoByPlacaRequest() {
        }
        
        public getEmitidoByPlacaRequest(sistemaAGP.IntegracionProvidencia.getEmitidoByPlacaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getEmitidoByPlacaRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string placa;
        
        public getEmitidoByPlacaRequestBody() {
        }
        
        public getEmitidoByPlacaRequestBody(string placa) {
            this.placa = placa;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getEmitidoByPlacaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getEmitidoByPlacaResponse", Namespace="http://tempuri.org/", Order=0)]
        public sistemaAGP.IntegracionProvidencia.getEmitidoByPlacaResponseBody Body;
        
        public getEmitidoByPlacaResponse() {
        }
        
        public getEmitidoByPlacaResponse(sistemaAGP.IntegracionProvidencia.getEmitidoByPlacaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getEmitidoByPlacaResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public sistemaAGP.IntegracionProvidencia.Pago getEmitidoByPlacaResult;
        
        public getEmitidoByPlacaResponseBody() {
        }
        
        public getEmitidoByPlacaResponseBody(sistemaAGP.IntegracionProvidencia.Pago getEmitidoByPlacaResult) {
            this.getEmitidoByPlacaResult = getEmitidoByPlacaResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getEmitidoByOperacionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getEmitidoByOperacion", Namespace="http://tempuri.org/", Order=0)]
        public sistemaAGP.IntegracionProvidencia.getEmitidoByOperacionRequestBody Body;
        
        public getEmitidoByOperacionRequest() {
        }
        
        public getEmitidoByOperacionRequest(sistemaAGP.IntegracionProvidencia.getEmitidoByOperacionRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getEmitidoByOperacionRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int IdOperacion;
        
        public getEmitidoByOperacionRequestBody() {
        }
        
        public getEmitidoByOperacionRequestBody(int IdOperacion) {
            this.IdOperacion = IdOperacion;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getEmitidoByOperacionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getEmitidoByOperacionResponse", Namespace="http://tempuri.org/", Order=0)]
        public sistemaAGP.IntegracionProvidencia.getEmitidoByOperacionResponseBody Body;
        
        public getEmitidoByOperacionResponse() {
        }
        
        public getEmitidoByOperacionResponse(sistemaAGP.IntegracionProvidencia.getEmitidoByOperacionResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getEmitidoByOperacionResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public sistemaAGP.IntegracionProvidencia.Pago getEmitidoByOperacionResult;
        
        public getEmitidoByOperacionResponseBody() {
        }
        
        public getEmitidoByOperacionResponseBody(sistemaAGP.IntegracionProvidencia.Pago getEmitidoByOperacionResult) {
            this.getEmitidoByOperacionResult = getEmitidoByOperacionResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getEmitidoByFechaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getEmitidoByFecha", Namespace="http://tempuri.org/", Order=0)]
        public sistemaAGP.IntegracionProvidencia.getEmitidoByFechaRequestBody Body;
        
        public getEmitidoByFechaRequest() {
        }
        
        public getEmitidoByFechaRequest(sistemaAGP.IntegracionProvidencia.getEmitidoByFechaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getEmitidoByFechaRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public System.DateTime FecPagoDesde;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public System.DateTime FecPagoHasta;
        
        public getEmitidoByFechaRequestBody() {
        }
        
        public getEmitidoByFechaRequestBody(System.DateTime FecPagoDesde, System.DateTime FecPagoHasta) {
            this.FecPagoDesde = FecPagoDesde;
            this.FecPagoHasta = FecPagoHasta;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getEmitidoByFechaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getEmitidoByFechaResponse", Namespace="http://tempuri.org/", Order=0)]
        public sistemaAGP.IntegracionProvidencia.getEmitidoByFechaResponseBody Body;
        
        public getEmitidoByFechaResponse() {
        }
        
        public getEmitidoByFechaResponse(sistemaAGP.IntegracionProvidencia.getEmitidoByFechaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getEmitidoByFechaResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public sistemaAGP.IntegracionProvidencia.Pago[] getEmitidoByFechaResult;
        
        public getEmitidoByFechaResponseBody() {
        }
        
        public getEmitidoByFechaResponseBody(sistemaAGP.IntegracionProvidencia.Pago[] getEmitidoByFechaResult) {
            this.getEmitidoByFechaResult = getEmitidoByFechaResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface svrAgpSoapChannel : sistemaAGP.IntegracionProvidencia.svrAgpSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class svrAgpSoapClient : System.ServiceModel.ClientBase<sistemaAGP.IntegracionProvidencia.svrAgpSoap>, sistemaAGP.IntegracionProvidencia.svrAgpSoap {
        
        public svrAgpSoapClient() {
        }
        
        public svrAgpSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public svrAgpSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public svrAgpSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public svrAgpSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        sistemaAGP.IntegracionProvidencia.getPagoByPlacaResponse sistemaAGP.IntegracionProvidencia.svrAgpSoap.getPagoByPlaca(sistemaAGP.IntegracionProvidencia.getPagoByPlacaRequest request) {
            return base.Channel.getPagoByPlaca(request);
        }
        
        public sistemaAGP.IntegracionProvidencia.Pago getPagoByPlaca(string placa) {
            sistemaAGP.IntegracionProvidencia.getPagoByPlacaRequest inValue = new sistemaAGP.IntegracionProvidencia.getPagoByPlacaRequest();
            inValue.Body = new sistemaAGP.IntegracionProvidencia.getPagoByPlacaRequestBody();
            inValue.Body.placa = placa;
            sistemaAGP.IntegracionProvidencia.getPagoByPlacaResponse retVal = ((sistemaAGP.IntegracionProvidencia.svrAgpSoap)(this)).getPagoByPlaca(inValue);
            return retVal.Body.getPagoByPlacaResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        sistemaAGP.IntegracionProvidencia.getPagoByOperacionResponse sistemaAGP.IntegracionProvidencia.svrAgpSoap.getPagoByOperacion(sistemaAGP.IntegracionProvidencia.getPagoByOperacionRequest request) {
            return base.Channel.getPagoByOperacion(request);
        }
        
        public sistemaAGP.IntegracionProvidencia.Pago getPagoByOperacion(int IdOperacion) {
            sistemaAGP.IntegracionProvidencia.getPagoByOperacionRequest inValue = new sistemaAGP.IntegracionProvidencia.getPagoByOperacionRequest();
            inValue.Body = new sistemaAGP.IntegracionProvidencia.getPagoByOperacionRequestBody();
            inValue.Body.IdOperacion = IdOperacion;
            sistemaAGP.IntegracionProvidencia.getPagoByOperacionResponse retVal = ((sistemaAGP.IntegracionProvidencia.svrAgpSoap)(this)).getPagoByOperacion(inValue);
            return retVal.Body.getPagoByOperacionResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        sistemaAGP.IntegracionProvidencia.getPagoByFechaResponse sistemaAGP.IntegracionProvidencia.svrAgpSoap.getPagoByFecha(sistemaAGP.IntegracionProvidencia.getPagoByFechaRequest request) {
            return base.Channel.getPagoByFecha(request);
        }
        
        public sistemaAGP.IntegracionProvidencia.Pago[] getPagoByFecha(System.DateTime FecPagoDesde, System.DateTime FecPagoHasta) {
            sistemaAGP.IntegracionProvidencia.getPagoByFechaRequest inValue = new sistemaAGP.IntegracionProvidencia.getPagoByFechaRequest();
            inValue.Body = new sistemaAGP.IntegracionProvidencia.getPagoByFechaRequestBody();
            inValue.Body.FecPagoDesde = FecPagoDesde;
            inValue.Body.FecPagoHasta = FecPagoHasta;
            sistemaAGP.IntegracionProvidencia.getPagoByFechaResponse retVal = ((sistemaAGP.IntegracionProvidencia.svrAgpSoap)(this)).getPagoByFecha(inValue);
            return retVal.Body.getPagoByFechaResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        sistemaAGP.IntegracionProvidencia.getEmitidoByPlacaResponse sistemaAGP.IntegracionProvidencia.svrAgpSoap.getEmitidoByPlaca(sistemaAGP.IntegracionProvidencia.getEmitidoByPlacaRequest request) {
            return base.Channel.getEmitidoByPlaca(request);
        }
        
        public sistemaAGP.IntegracionProvidencia.Pago getEmitidoByPlaca(string placa) {
            sistemaAGP.IntegracionProvidencia.getEmitidoByPlacaRequest inValue = new sistemaAGP.IntegracionProvidencia.getEmitidoByPlacaRequest();
            inValue.Body = new sistemaAGP.IntegracionProvidencia.getEmitidoByPlacaRequestBody();
            inValue.Body.placa = placa;
            sistemaAGP.IntegracionProvidencia.getEmitidoByPlacaResponse retVal = ((sistemaAGP.IntegracionProvidencia.svrAgpSoap)(this)).getEmitidoByPlaca(inValue);
            return retVal.Body.getEmitidoByPlacaResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        sistemaAGP.IntegracionProvidencia.getEmitidoByOperacionResponse sistemaAGP.IntegracionProvidencia.svrAgpSoap.getEmitidoByOperacion(sistemaAGP.IntegracionProvidencia.getEmitidoByOperacionRequest request) {
            return base.Channel.getEmitidoByOperacion(request);
        }
        
        public sistemaAGP.IntegracionProvidencia.Pago getEmitidoByOperacion(int IdOperacion) {
            sistemaAGP.IntegracionProvidencia.getEmitidoByOperacionRequest inValue = new sistemaAGP.IntegracionProvidencia.getEmitidoByOperacionRequest();
            inValue.Body = new sistemaAGP.IntegracionProvidencia.getEmitidoByOperacionRequestBody();
            inValue.Body.IdOperacion = IdOperacion;
            sistemaAGP.IntegracionProvidencia.getEmitidoByOperacionResponse retVal = ((sistemaAGP.IntegracionProvidencia.svrAgpSoap)(this)).getEmitidoByOperacion(inValue);
            return retVal.Body.getEmitidoByOperacionResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        sistemaAGP.IntegracionProvidencia.getEmitidoByFechaResponse sistemaAGP.IntegracionProvidencia.svrAgpSoap.getEmitidoByFecha(sistemaAGP.IntegracionProvidencia.getEmitidoByFechaRequest request) {
            return base.Channel.getEmitidoByFecha(request);
        }
        
        public sistemaAGP.IntegracionProvidencia.Pago[] getEmitidoByFecha(System.DateTime FecPagoDesde, System.DateTime FecPagoHasta) {
            sistemaAGP.IntegracionProvidencia.getEmitidoByFechaRequest inValue = new sistemaAGP.IntegracionProvidencia.getEmitidoByFechaRequest();
            inValue.Body = new sistemaAGP.IntegracionProvidencia.getEmitidoByFechaRequestBody();
            inValue.Body.FecPagoDesde = FecPagoDesde;
            inValue.Body.FecPagoHasta = FecPagoHasta;
            sistemaAGP.IntegracionProvidencia.getEmitidoByFechaResponse retVal = ((sistemaAGP.IntegracionProvidencia.svrAgpSoap)(this)).getEmitidoByFecha(inValue);
            return retVal.Body.getEmitidoByFechaResult;
        }
    }
}
